### PR TITLE
Fixing initialization of external vector potential when using periodi…

### LINKED ISSUE #5983: A_external initialization error in 2D Hybrid-PIC simulation
## Description
2D Hybrid-PIC turbulence simulation fails during initialization when using `A_external` to introduce constant background magnetic field By=B0 with periodic boundaries.

**Working**: `AnalyticInitialField` with `By_expression=B0`
**Failing**: `A_external=(0, 0, -x*B0)` (generates same By=B0 via curl A)

Error: `Assertion 'Efield_fp[lev][idim]->is_finite()' failed` during `simulation.initialize_warpx()`

## Expected behavior
Both methods should behave identically since they generate the same magnetic field distribution.

## How to reproduce
**Run command:**
```bash
mpirun -np 8 python3 turbulence_issues.py
```

**Working configuration:**
```python
B_ext = picmi.AnalyticInitialField(
    Bx_expression=self.Bx, 
    By_expression=self.By,  # By = B0
    Bz_expression=self.Bz
)
```

**Failing configuration:**
```python
B_ext = picmi.AnalyticInitialField(
    Bx_expression=self.Bx, 
    By_expression="0",  # No initial By
    Bz_expression=self.Bz
)

A_ext = {
    "uniform_analytical": {
        "Ax_external_function": "0",
        "Ay_external_function": "0", 
        "Az_external_function": f"-x*{self.B0}",
        "A_time_external_function": "1",
    }
}
```

**Workarounds**: Increase substeps (10→500) or use periodic A_external like `cos(2*pi/Lx*x)`

## System information
- [x] Linux: Ubuntu 24.04 LTS (WSL2)
- Version of WarpX: PR #5956
- [x] From source with CMake
- [x] MPI: 8 

## Steps taken so far
1. Tested workarounds (substeps, periodic A_external)
2. Confirmed error occurs during initialization only

## Additional information
- 2D Cartesian (x-z) with periodic boundaries
- HybridPICSolver
- A_external: `Az = -x*B0` (non-periodic function, periodic B field)

**Key questions:**
1. Self-consistency issue between plasma and A_external-generated field?
2. Bug in A_external implementation with periodic boundaries?
3. Numerical stability issue in initialization phase?

@clarkse - This appears related to our previous discussion about A_external. Could you investigate whether this is a self-consistency issue or a code bug?

**Attached**: `turbulence_issues.py` (reproducible test case) 

[turbulence_issues.txt](https://github.com/user-attachments/files/20961581/turbulence_issues.txt)

### PR DESCRIPTION
**Pull request by clarkse**
…c BCs and non-zero initial value.

Fix #5983

### CODE REVIEW

File: Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/ExternalVectorPotential.cpp [hunk 1]
```diff
@@ -199,12 +201,9 @@ ExternalVectorPotential::InitData ()
...
                     warpx.GetEBUpdateEFlag(),
                     false);
-
-                for (int idir = 0; idir < 3; ++idir) {
-                    warpx.m_fields.get(Aext_field, Direction{idir}, lev)->
-                        FillBoundary(warpx.Geom(lev).periodicity());
-                }
             }
+            // NOTE: Fill Boundary is not done here since non-periodic A fields can lead to periodic E/B fields
+            // This requires valid definitions of the vector potential in the ghost cells.
```
Comment (roelof-groenewald) [inline Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/ExternalVectorPotential.cpp:206]: But without `FillBoundary` wouldn't the internal guard cells be unspecified?

Comment (clarkse) [reply Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/ExternalVectorPotential.cpp:206]: The loop that fills the array from implicit function is run over all cells including guard cells, so they are populated. The interpolation from file does the same, so it should be fine.

Comment (clarkse) [reply Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/ExternalVectorPotential.cpp:206]: Additionally, if doing the div cleaning for a Coulomb Gauge potential, which is incompatible with non-periodic vector potentials when using periodic field boundaries, it should apply a FillBoundary after the removal of the divergence components.

Comment (roelof-groenewald) [reply Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/ExternalVectorPotential.cpp:206]: Cool! Sounds good!

**Review by roelof-groenewald — APPROVED** [review]
